import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import { ThemeSwitcher } from "@/components/theme-switcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen bg-background text-foreground">
            <header className="flex flex-col sm:flex-row justify-between items-center px-4 sm:px-6 lg:px-8 py-4 border-b border-border">
              <div className="text-3xl font-bold text-primary mb-4 sm:mb-0">
                <Link href="/">Turks and Caicos News Aggregator</Link>
              </div>
              <div className="flex items-center space-x-4">
                <nav>
                  <ul className="flex space-x-4">
                    <li><Link href="/" className="text-muted-foreground hover:text-foreground transition-colors">Home</Link></li> {/* Added Home link */}
                    <li><Link href="/admin" className="text-muted-foreground hover:text-foreground transition-colors">Admin</Link></li>
                    <li><Link href="/admin/sources" className="text-muted-foreground hover:text-foreground transition-colors">Manage Sources</Link></li> {/* Added Manage Sources link */}
                  </ul>
                </nav>
                <ThemeSwitcher />
              </div>
            </header>
            <main className="flex-grow container mx-auto px-4 py-8 sm:px-6 lg:px-8">
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
